### ISSUE TITLE
NoClassDefFoundError: com.google.android.gms.common.AccountPicker

### ISSUE THREAD

**Issue by christor54** [christor54/Authentication_Prototype#3]
```
   at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential.newChooseAccountIntent(GoogleAccountCredential.java:231)
        at ctprojects.authentication_prototype.MainActivity.chooseAccount(MainActivity.java:86)
        at ctprojects.authentication_prototype.MainActivity.onCreate(MainActivity.java:48)
```

**Comment by christor54** [comment]
Need to import google play service
Add in gradle of the app

dependencies {

```
compile 'com.google.android.gms:play-services:6.5.87'
```

}
